on: 
 push:
#   paths:
#     -'**.py'
    
name: Python-Test
jobs:
  python-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
#     - uses: konstruktoid/action-pylint@v0.2.3
    - uses: DataDog/action-py-black-formatter@v2.5
    - uses: actions/setup-python@v4.7.0
    - run: python3 test.py
 
