on: 
 push:
  paths:
    -'**.py'
    
name: Python-Test
jobs:
  test:
    runs-on: self.hosted
    steps:
    - uses: actions/checkout@master
    - name: PyInstaller Linux amd64
      id: amd64
      uses: action-python/pyinstaller-py3.7@amd64
      with:
        path: .
 
