on: 
 push:
  paths:
    -'**.py'
    
name: Python-Test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3     
    - uses: actions/setup-python@v4.7.0
    - run: python3 test.py
 
